name: docker build
on:
  push:
    branches:
      - master

jobs:
  prowlarr:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: prowlarr-dev
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: prowlarr-dev
          run_args: -e API_KEY=gitaction
          curl: :9696/api/v1/system/status
          curl_opts: --header x-api-key:gitaction
          pipe: |
            jq -r ".version" |
            grep -qw "$(label org.label-schema.version)"
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: prowlarr-dev
          repo: ${{ secrets.docker_username }}/prowlarr
          tags: latest,%label org.label-schema.version | %auto
      - name: docker-scout
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ secrets.docker_username }}
          dockerhub-password: ${{ secrets.docker_password }}
          command: cves
          image: ${{ secrets.docker_username }}/prowlarr:latest
